name: Automated Workflow
on: 
  push:
    branches: 
      - 'master'
      - 'fork'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Display Info"
      run: echo "ref = ${{ github.ref }}, sha = ${{ github.sha }}"
    - name: "Print Message"
      run: echo "Hello from 'fork'"